/**
 * Data Loader Service
 * @module services/dataLoader
 * 
 * Loads PR metrics data from pr_metrics.json file generated by workflows
 */

import { STRINGS } from '../resources/strings.js';

/**
 * Load PR metrics from JSON file
 * @returns {Promise<Array>} Array of PR metrics
 */
export async function loadPRMetrics() {
    try {
        console.log('📂 Loading PR metrics from JSON file...');

        // Fetch the pr_metrics.json file from the root directory
        const response = await fetch('pr_metrics.json');

        if (!response.ok) {
            throw new Error(`Failed to load pr_metrics.json: ${response.status} ${response.statusText}`);
        }

        const rawData = await response.json();

        // Transform the data to dashboard format
        const transformedData = rawData.map(pr => transformPRData(pr));

        console.log(`✅ Loaded ${transformedData.length} PRs from pr_metrics.json`);
        return transformedData;
    } catch (error) {
        console.error('❌ Error loading PR metrics:', error);
        throw new Error(`Failed to load PR metrics: ${error.message}`);
    }
}

/**
 * Transform workflow JSON format to dashboard format
 * @param {Object} pr - PR data from pr_metrics.json
 * @returns {Object} Transformed PR object
 */
function transformPRData(pr) {
    // Extract reviewers from approvals
    const reviewers = pr.approvals.map(approval => approval.reviewer.login);

    // Extract commenters and total comments from grouped comment structure
    // Workflow provides: [{author: {login: "user1"}, count: 3}, ...]
    const commenters = pr.comments.map(comment => comment.author?.login).filter(Boolean);
    const totalComments = pr.comments.reduce((sum, comment) => sum + (comment.count || 0), 0);

    // Find first reviewer
    const firstReviewer = pr.approvals.length > 0 ? pr.approvals[0].reviewer.login : null;

    return {
        number: pr.pr_number,
        title: pr.title,
        url: pr.url,
        author: pr.creator.login,
        status: pr.status, // 'pending', 'approved', 'merged', 'closed'
        createdAt: pr.opened_at,
        mergedAt: pr.merged_at,
        approvedAt: pr.first_approved_at,
        mergedBy: pr.merged_by ? pr.merged_by.login : null,
        additions: pr.diff_stats?.additions || 0,
        deletions: pr.diff_stats?.deletions || 0,
        comments: totalComments, // Total count of all comments
        approvals: pr.approvals.length,
        reviewers: reviewers,
        commenters: commenters, // Unique users who commented
        timeToFirstApproval: pr.time_to_first_approval_minutes,
        firstReviewer: firstReviewer,
        // New fields from workflow enhancements
        labels: pr.labels || [],
        milestone: pr.milestone,
        draft: pr.draft || false,
        reviewRequests: pr.review_requests || [],
        filesChanged: pr.files_changed || []
    };
}

/**
 * Check if pr_metrics.json file exists and is accessible
 * @returns {Promise<boolean>} True if file exists and is accessible
 */
export async function isDataAvailable() {
    try {
        const response = await fetch('pr_metrics.json', { method: 'HEAD' });
        return response.ok;
    } catch (error) {
        return false;
    }
}
