name: sellio_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_gap: ^1.2.0
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.2.1
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik_regular.ttf
          weight: 400
        - asset: assets/fonts/rubik_medium.ttf
          weight: 500
        - asset: assets/fonts/rubik_semi_bold.ttf
          weight: 600

flutter_native_splash:
  color: "#F8F8F8"
  color_dark: "#1F1F1F"

  image: assets/images/sellio_splash.png
  image_dark: assets/images/sellio_splash.png

  ios_content_mode: center

  # For Android 12+
  android_12:
    image: assets/images/sellio_splash.png
    image_dark: assets/images/sellio_splash.png
    color: "#F8F8F8"
    color_dark: "#1F1F1F"

# ---- flutter_launcher_icons ----
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sellio.png"


