name: authentication
description: "Authentication package for Sellio monorepo"
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  core:
    path: ../core
  design_system:
    path: ../design_system

  # UI Dependencies
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_gap: ^1.0.2
  intl: ^0.20.0
  shimmer: ^4.0.0
  flutter_intl_phone_field: ^0.0.7
  country_picker: ^2.0.27
  country_flags: ^4.1.2

  # Networking
  dio: ^5.7.0

  # Dependency Injection
  get_it: ^9.2.1

  # State Management
  equatable: ^2.1.0
  flutter_bloc: ^9.1.1

  # Freezed Serialization
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Navigation
  go_router: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  freezed: ^4.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true