name: seller
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  design_system:
    path: ../../packages/design_system

  core:
    path: ../../packages/core

  authentication:
    path: ../../packages/authentication

  # UI Dependencies
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_gap: ^1.0.2
  intl: ^0.20.0
  shimmer: ^4.0.0

  # Networking
  dio: ^5.7.0

  # Dependency Injection
  get_it: ^9.2.1

  # Local Storage
  shared_preferences: ^2.2.3

  # Network Info
  internet_connection_checker: ^3.0.1

  # Navigation
  go_router: ^18.0.0

  # State Management
  equatable: ^2.1.0
  flutter_bloc: ^9.1.1

  # Country Picker
  country_picker: ^2.0.27
  country_detector: ^1.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true

flutter_native_splash:
  color: "#F8F8F8"
  image: ../../packages/design_system/assets/images/sellio_splash.png
  ios_content_mode: center

  android_12:
    image: ../../packages/design_system/assets/images/sellio_splash.png
    color: "#F8F8F8"

  web: false
  fullscreen: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../../packages/design_system/assets/images/sellio_splash.png"
  adaptive_icon_background: "#F8F8F8"
  adaptive_icon_foreground: "../../packages/design_system/assets/images/sellio_splash.png"
