name: sellio_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  design_system:
    path: ../../packages/design_system

  # UI Dependencies
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_gap: ^1.0.2
  intl: ^0.20.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.2.0

  # Dependency Injection
  get_it: ^7.7.0

  # Local Storage
  path: ^1.9.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^8.0.0

  # Network Info
  internet_connection_checker: ^1.0.0+1

  # Functionality
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.9.0
  go_router: ^16.3.0

  # State Management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

  # Freezed Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and tooling
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

  # Freezed Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true

  # Fonts
  # fonts:
  #   - family: Rubik
  #     fonts:
  #       - asset: packages/design_system/assets/fonts/rubik_regular.ttf
  #         weight: 400
  #       - asset: packages/design_system/assets/fonts/rubik_medium.ttf
  #         weight: 500
  #       - asset: packages/design_system/assets/fonts/rubik_semi_bold.ttf
  #         weight: 600

flutter_native_splash:
  color: "#F8F8F8"
  image: ../../packages/design_system/assets/images/sellio_splash.png
  ios_content_mode: center

  android_12:
    image: ../../packages/design_system/assets/images/sellio_splash.png
    color: "#F8F8F8"

  web: false
  fullscreen: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../../packages/design_system/assets/images/sellio_splash.png"
  adaptive_icon_background: "#F8F8F8"
  adaptive_icon_foreground: "../../packages/design_system/assets/images/sellio_splash.png"